# Generated by Django 3.1.5 on 2021-12-14 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20211214_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='driver_id',
            new_name='driver',
        ),
    ]
